services:
  ############## FrontEnd NGX with CSP ################
  # 2. build the final nginx image with csp configured
  bsl-nginx:
    build:
      dockerfile: Dockerfile
      context: .
      tags:
        - "browser-security-lab"
    volumes:
      - ./nginx/local:/usr/share/nginx-config:rw
      - ./nginx/conf:/etc/nginx/templates
    environment:
      - NGINX_ERR_OUTPUT=/dev/stdout
      - NGINX_ERR_MODE=info
      - NGINX_CONFIG_FILE=/usr/share/nginx-config/csp-policy.conf
      # log all csp errors to the logger
      - NGX_CSP_REPORTING_SERVER='https://localhost:9999'
    image: "browser-security-lab-image"
    container_name: "browser-security-lab"
    ports:
      - "7777:80"
      - "9081:8080"
      - "9381:8443"

  ################# CSP REPORTER ####################
  # where to send the csp reports
  nginx-csp-reporter:
    image: ghcr.io/ix-ai/csp:latest
    container_name: csp-reporter
    environment:
      PORT: "9999"
      MAX_CONTENT_LENGTH: "40000"
    ports:
      - "9999:9999"
