services:
  ############## FrontEnd NGX with CSP ################
  # 2. build the final nginx image with csp configured
  bsl-nginx:
    build:
      dockerfile: Dockerfile
      context: .
      tags:
        - "browser-security-lab"
      args:
        # two nginx config files that the user can dynamically change
        # this is for most nginx cors and csp headers
        NGINX_CSP_CONFIG_FILE: /usr/share/nginx-config/ngx-csp-update-file.conf
        # this is for cors preflight requests
        NGINX_CORS_CONFIG_FILE: /usr/share/nginx-config/ngx-dynamic-cors-update-file.conf
        NGINX_PF_CORS_CONFIG_FILE: /usr/share/nginx-config/ngx-dynamic-preflight-cors-update-file.conf
    volumes:
      - ./nginx/local:/usr/share/nginx-config:rw
      - ./nginx/conf:/etc/nginx/templates
    environment:
      - NGINX_ERR_OUTPUT=/dev/stdout
      - NGINX_ERR_MODE=info
      - NGX_CSP_REPORTING_SERVER="https://localhost:9800"
      - NGINX_HTML_ROOT=/usr/local/openresty/nginx/html/
    image: "browser-security-lab-image"
    container_name: "browser-security-lab"
    ports:
      - "7777:80"    # bsl front end HTML and JS server
      - "9081:8080"  # csp backend
      - "9381:8443"  # csp ssl backend
      - "9090:9090" #  cors backend
      - "9443:9443" #  cors ssl backend


  ################# CSP REPORTER ####################
  # where to send the csp reports
  #nginx-csp-reporter:
  #  image: ghcr.io/ix-ai/csp:latest
  #  container_name: csp-reporter
  #  environment:
  #    PORT: "9800"
  #    MAX_CONTENT_LENGTH: "40000"
  #  ports:
  #    - "9800:9800"
