services:
    ############## BackEnd ################
    # dockerized backend, no debug
    bsl-backend:
        build:
            dockerfile: src/Dockerfile
            context: .
            tags:
                - 'bsl-backend:latest'
        volumes:
            - /home/dreez/repos/Browser-Security-Lab/nginx/local:/usr/share/nginx-config
        container_name: bsl-backend
        ports:
            - '9081:9081'
            - '9381:9381'
            - '3000:3000'
            - '3300:3300'
            - '3100:3100'
            - '3400:3400'

    ############## FrontEnd NGX with CSP ################
    # 2. build the final nginx image with csp configured
    bsl-final-cspngx:
        build:
            dockerfile: nginx/Dockerfile.Final-CspNgx
            context: .
            tags:
                - 'bsl-nginx-csp-frontend:latest'
        depends_on:
            - bsl-backend
        volumes:
            - /home/dreez/repos/Browser-Security-Lab/nginx/local:/usr/share/nginx-config
        environment: # environment variables for the container
            # tell ngx to pass all API calls to backend
            NGX_BACKEND: 'https://localhost:9381'
            # ngx debug level
            NGX_LOG_LEVEL: 'warn'
            # log all csp errors to the logger
            NGX_CSP_REPORTING_SERVER: 'https://localhost:9999'
        image: 'bsl-nginx-csp-frontend:latest'
        container_name: bsl-nginx-csp-frontend
        ports:
            - '7777:80'

    ################# CSP REPORTER ####################
    # where to send the csp reports
    nginx-csp-reporter:
        image: ghcr.io/ix-ai/csp:latest
        environment:
            PORT: '9999'
            MAX_CONTENT_LENGTH: '40000'
        ports:
            - '9999:9999'
        depends_on:
            - bsl-final-cspngx
